apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
      - name: react-app
        image:  jenkinstest09.azurecr.io/jenkinstest09:latest
        imagePullPolicy: Always
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: react-app
    k8s-app: react-app
  name: react-app
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  type: NodePort
  selector:
    app: react-app
